export const AUTH_LOGIN_STACK_NAVIGATOR = 'AUTH_LOGIN_STACK';
export const AUTH_LOGIN_SCREEN = 'LOGIN_SCREEN';
export const AUTH_REGISTER_SCREEN = 'AUTH_REGISTER_SCREEN';

export const MAIN_TAB_NAVIGATOR = 'MAIN_TAB_NAVIGATOR';
export const USER_TAB_NAVIGATOR = 'USER_TAB_NAVIGATOR';
export const WORKER_TAB_NAVIGATOR = 'WORKER_TAB_NAVIGATOR'